Origin/task/file reader service
seeeverything/tool.database-script-runner pull request #12
Opened 2021-07-12 04:39 UTC by mdomanoski

2021-07-12 04:48 UTC, tejashari1 commented on src/Tool.DatabaseScriptRunner.Console/Services/FileHandlerService.cs
> +            {
Would we want to have the files == null check in GetControlFile method as well?

2021-07-12 04:56 UTC, dave-wharton requested changes
just one comment!

2021-07-12 04:56 UTC, dave-wharton commented on src/Tool.DatabaseScriptRunner.Console/Services/FileHandlerService.cs
> +                throw new ScriptFileException("No script files found");
Perhaps ArgumentNullException is what should be thrown here?

2021-07-12 21:31 UTC, mdomanoski commented on src/Tool.DatabaseScriptRunner.Console/Services/FileHandlerService.cs
> +            {
Yea, I added this check to the other method too. Thanks

2021-07-12 21:32 UTC, mdomanoski commented on src/Tool.DatabaseScriptRunner.Console/Services/FileHandlerService.cs
> +                throw new ScriptFileException("No script files found");
I replaced the previous exception type to ArgumentNullException. Thanks

2021-07-12 22:36 UTC, jvmcruz commented on src/Tool.DatabaseScriptRunner.Console/Services/FileHandlerService.cs
> +                throw new ArgumentNullException("No script files found");
maybe it should just be "files" rather than "script files" because at this point we're checking for any file.

2021-07-12 22:36 UTC, jvmcruz commented on src/Tool.DatabaseScriptRunner.Console/Services/FileHandlerService.cs
> +                throw new ArgumentNullException("No script files found");
also, should we use `.Any()` instead?

2021-07-12 22:37 UTC, jvmcruz commented on src/Tool.DatabaseScriptRunner.Console/Services/FileHandlerService.cs
> +            if (files == null)
same comment as above

2021-07-12 22:39 UTC, jvmcruz commented on src/Tool.DatabaseScriptRunner.Console/Services/FileHandlerService.cs
> +            return JsonConvert.DeserializeObject<ControlFile>(controlFiles[0].Content);
should we use `First()` instead?

2021-07-13 02:22 UTC, mdomanoski commented on src/Tool.DatabaseScriptRunner.Console/Services/FileHandlerService.cs
> +                throw new ArgumentNullException("No script files found");
Corrected the files string.

Added **!files.Any()** as "or" condition since it can error if we dont have a null check. Thanks!

2021-07-13 02:22 UTC, mdomanoski commented on src/Tool.DatabaseScriptRunner.Console/Services/FileHandlerService.cs
> +            if (files == null)
Done as above.

2021-07-13 03:05 UTC, jvmcruz commented on src/Tool.DatabaseScriptRunner.Console/Services/FileHandlerService.cs
> +            return JsonConvert.DeserializeObject<ControlFile>(controlFiles.FirstOrDefault().Content);
this can be made `.First()` because it should always have 1.

2021-07-13 03:10 UTC, mdomanoski commented on src/Tool.DatabaseScriptRunner.Console/Services/FileHandlerService.cs
> +            return JsonConvert.DeserializeObject<ControlFile>(controlFiles.FirstOrDefault().Content);
True, it will never be null since it would cause the exception above. Corrected.

2021-07-13 03:12 UTC, jvmcruz submitted a review, later dismissed
nice work 🥇

2021-07-13 03:19 UTC, merged