FileHandlerService Unit Tests
seeeverything/tool.database-script-runner pull request #20
Opened 2021-07-13 04:17 UTC by mdomanoski

Unit test for 2 methods on the service:
GetControlFile()
GetScriptFiles()

2021-07-13 21:22 UTC, tejashari1 requested changes
A few things to look at

2021-07-13 21:22 UTC, tejashari1 commented on test/Tool.DatabaseScriptRunner.Console.UnitTests/Services/FileHandlerServiceUnitTests.cs
> +        public void Then_It_Should_Return_ControlFile_Content_When_Found_On_GetControlFile()
Just the naming. I don't think "_On_GetControlFile()" is needed at the end. And the other test names as well

2021-07-13 21:22 UTC, tejashari1 commented on test/Tool.DatabaseScriptRunner.Console.UnitTests/Services/FileHandlerServiceUnitTests.cs
> +            var fileHandlerService = new FileHandlerService();
I think we should be calling the Mock Interface here?

2021-07-13 21:22 UTC, tejashari1 commented on test/Tool.DatabaseScriptRunner.Console.UnitTests/Services/FileHandlerServiceUnitTests.cs
> +            var fileHandlerService = new FileHandlerService();
same here and everywhere else

2021-07-13 22:52 UTC, mdomanoski commented on test/Tool.DatabaseScriptRunner.Console.UnitTests/Services/FileHandlerServiceUnitTests.cs
> +        public void Then_It_Should_Return_ControlFile_Content_When_Found_On_GetControlFile()
Removed

2021-07-13 22:53 UTC, mdomanoski commented on test/Tool.DatabaseScriptRunner.Console.UnitTests/Services/FileHandlerServiceUnitTests.cs
> +            var fileHandlerService = new FileHandlerService();
As discussed with TJ, we dont need to mock anything since nothing is injected into the service interface

2021-07-13 22:53 UTC, mdomanoski commented on test/Tool.DatabaseScriptRunner.Console.UnitTests/Services/FileHandlerServiceUnitTests.cs
> +            var fileHandlerService = new FileHandlerService();
Same as above

2021-07-14 02:35 UTC, tejashari1 requested changes

2021-07-14 02:35 UTC, tejashari1 commented on src/Tool.DatabaseScriptRunner.Console/ProcessorService.cs
> +                    _logger.Information($"No files found for client {client.Name}");
I would suggest a slightly more detailed message. Maybe "No files found to process for client {client.Name}"

2021-07-14 02:35 UTC, tejashari1 commented on test/Tool.DatabaseScriptRunner.Console.UnitTests/ProcessorServiceUnitTest.cs
> +        public async Task Then_It_Should_Return_When_Files_Are_Empty()
Just the naming: Then_It_Should_Return_When_FileList_Is_Empty

2021-07-14 02:35 UTC, tejashari1 commented on test/Tool.DatabaseScriptRunner.Console.UnitTests/ProcessorServiceUnitTest.cs
> +        public async Task Then_It_Should_Return_When_Files_Are_Null()
Then_It_Should_Return_When_FileList_Is_Null would be my naming suggestion

2021-07-14 03:21 UTC, mdomanoski commented on src/Tool.DatabaseScriptRunner.Console/ProcessorService.cs
> +                    _logger.Information($"No files found for client {client.Name}");
Added

2021-07-14 03:21 UTC, mdomanoski commented on test/Tool.DatabaseScriptRunner.Console.UnitTests/ProcessorServiceUnitTest.cs
> +        public async Task Then_It_Should_Return_When_Files_Are_Empty()
Changed

2021-07-14 03:22 UTC, mdomanoski commented on test/Tool.DatabaseScriptRunner.Console.UnitTests/ProcessorServiceUnitTest.cs
> +        public async Task Then_It_Should_Return_When_Files_Are_Null()
Changed

2021-07-14 03:34 UTC, tejashari1 approved these changes

2021-07-14 03:58 UTC, merged