Extend the database implementations to handle TSQL code
seeeverything/tool.database-script-runner pull request #9
Opened 2021-07-12 03:09 UTC by tejashari1

2021-07-12 03:14 UTC, dave-wharton requested changes
Just some comments! maybe just check in the interface until you are ready?

2021-07-12 03:14 UTC, dave-wharton commented on src/Tool.DatabaseScriptRunner.Database/Models/MigrationRunner.cs
> +                ApplyMigration(unAppliedMigration).Wait();
Why are you waiting?

2021-07-12 03:14 UTC, dave-wharton commented on src/Tool.DatabaseScriptRunner.Database/TSql/SqlMigrationRunner.cs
> +                    throw new Exception();
Why just throwing a empty exception?

2021-07-12 03:14 UTC, dave-wharton commented on src/Tool.DatabaseScriptRunner.Database/TSql/SqlMigrationRunner.cs
> +                    ApplyMigration(unAppliedMigration).Wait();
Same here around the wait

2021-07-12 04:25 UTC, tejashari1 commented on src/Tool.DatabaseScriptRunner.Database/TSql/SqlMigrationRunner.cs
> +                    ApplyMigration(unAppliedMigration).Wait();
removed

2021-07-12 04:25 UTC, tejashari1 commented on src/Tool.DatabaseScriptRunner.Database/TSql/SqlMigrationRunner.cs
> +                    throw new Exception();
removed logging as it will be handled in try catch block in Processor... Have added detailed exception here

2021-07-12 04:25 UTC, tejashari1 commented on src/Tool.DatabaseScriptRunner.Database/Models/MigrationRunner.cs
> +                ApplyMigration(unAppliedMigration).Wait();
removed

2021-07-12 05:02 UTC, dave-wharton reviewed
Just a couple of more comments! i might be a bit confused about what you are trying to do!

2021-07-12 05:02 UTC, dave-wharton commented on src/Tool.DatabaseScriptRunner.Database/Extensions/PostgresExtensions.cs
> +                await new PostgresMigrationRunner(repository, logger).Apply();
Why is this Postgress? Are we supporting both. Sorry! Just a bit confused...

2021-07-12 05:02 UTC, dave-wharton commented on src/Tool.DatabaseScriptRunner.Database/Extensions/PostgresExtensions.cs
> +            return services.AddDatabaseConnection(configuration).Result
Why not await here?

2021-07-12 05:10 UTC, tejashari1 commented on src/Tool.DatabaseScriptRunner.Database/Extensions/PostgresExtensions.cs
> +                await new PostgresMigrationRunner(repository, logger).Apply();
This is existing code that gets called by the extensions class when adding database connection during startup.. We are not using this or calling it. But since I changed the ApplyMigrations to be awaitable, I needed to change the Apply() method to return async Task. And therefore, this needed to change to await.

2021-07-12 05:13 UTC, tejashari1 commented on src/Tool.DatabaseScriptRunner.Database/Extensions/PostgresExtensions.cs
> +            return services.AddDatabaseConnection(configuration).Result
We are just calling the AddDatabaseConnection and AddDbContext (which is a built in method). I don't think we can change this to await without changing the logic?

2021-07-12 23:37 UTC, jvmcruz commented on src/Tool.DatabaseScriptRunner.Database/MigrationRunner.cs
> +        public async Task Apply(string connectionString, List<IMigration> migrations = null)
should we break this method down? on top of applying the migrations, it looks like it's trying to check for migration changes and get un-applied migrations too

2021-07-12 23:39 UTC, gabmoronintilecta reviewed
just a couple of comments!

2021-07-12 23:39 UTC, gabmoronintilecta commented on src/Tool.DatabaseScriptRunner.Database/MigrationRunner.cs
> +                var changedMigration = migrations.First(migration => HasMigrationChanged(migration, appliedMigrations));
If we use First(), it means this will throw an error if it doesn't find it. Based on the condition above I guess it won't happen but maybe we still want to use FirstOrDefault?

2021-07-12 23:39 UTC, gabmoronintilecta commented on src/Tool.DatabaseScriptRunner.Database/TSql/SqlMigrationRunner.cs
> +                go";
I know this was on the original implementation and we haven't really spoken about this, but do we want to keep table and column names lower case, or we want to user our standard? 
Same for the SQL Sintax itself when using reserved keywords like "create table", etc.

2021-07-12 23:50 UTC, tejashari1 commented on src/Tool.DatabaseScriptRunner.Database/MigrationRunner.cs
> +        public async Task Apply(string connectionString, List<IMigration> migrations = null)
Hi JV, this apply method is not just applying the migrations, it is pretty much a Run() or DoWork() method in the MigrationRunner. It gets migrations, applied migrations and unapplied migrations which are all in their own methods so I think this is okay

2021-07-12 23:53 UTC, tejashari1 commented on src/Tool.DatabaseScriptRunner.Database/MigrationRunner.cs
> +                var changedMigration = migrations.First(migration => HasMigrationChanged(migration, appliedMigrations));
corrected

2021-07-12 23:55 UTC, tejashari1 commented on src/Tool.DatabaseScriptRunner.Database/Extensions/PostgresExtensions.cs
> +                await new PostgresMigrationRunner(repository, logger).Apply();
Updated

2021-07-12 23:55 UTC, tejashari1 commented on src/Tool.DatabaseScriptRunner.Database/Extensions/PostgresExtensions.cs
> +            return services.AddDatabaseConnection(configuration).Result
updated

2021-07-13 00:03 UTC, tejashari1 commented on src/Tool.DatabaseScriptRunner.Database/TSql/SqlMigrationRunner.cs
> +                go";
Yeah, good idea. But when we insert to the table, the base class is using lowercases which is shared between both postgres and sql migration runner. So this will require further work (potentially more overrides) to have slightly different naming convention.

2021-07-13 00:45 UTC, gabmoronintilecta approved these changes

2021-07-13 00:47 UTC, merged